version: '3.8'

services:
  strapi-prod:
    container_name: strapi-prod
    build: 
      context: ../..
      dockerfile: Dockerfile
    image: strapi-prod:latest
    restart: always
    env_file: .env
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: ${DATABASE_CLIENT:-postgres}
      DATABASE_HOST: ${DATABASE_HOST:-strapi_db}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_NAME: ${DATABASE_NAME:-strapi}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-strapi}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-strapi}
      DATABASE_SSL: ${DATABASE_SSL:-false}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      GCS_SERVICE_ACCOUNT_KEY_PATH: ${GCS_SERVICE_ACCOUNT_KEY_PATH}
   
    volumes:
      - ./tathata-460206-c3848c9360ef.json:/opt/app/GCServiceAccountKey.json:ro

    ports:
      - '1337:1337'
    networks:
      - strapi-net


networks:
  strapi-net:
    driver: bridge
