version: '3.8'

services:
  strapi-dev:
    container_name: strapi-dev
    build: 
      context: ..
      dockerfile: Dockerfile
    image: strapi-dev:latest
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: development
    volumes:
      - ../config:/opt/app/config
      - ../src:/opt/app/src
      - ../package.json:/opt/app/package.json
      - ../package-lock.json:/opt/app/package-lock.json
      - ../.tmp:/opt/app/.tmp
      - ../public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - strapi-net

networks:
  strapi-net:
    driver: bridge
